### ISSUE TITLE
React packager issue - prelude_dev.js not found in any of the roots

### ISSUE THREAD

**Issue by pkovacevic** [ReactWindows/react-native#390]
I'm having this issue when starting Playground application.
What I did:

- cloned repo and positioned myself in /react-native
- npm install
- node local-cli/cli.js start
- Started playground application which sent a request.

Following issue occured:
![image](https://cloud.githubusercontent.com/assets/928809/14771473/6b281bc8-0a8c-11e6-8cad-bf2945a89643.png)

I'm using Windows 10
npm version 3.8.7
node version v5.10.1

Of course, prelude_dev.js can be found at searched directory (C:\react-native\packager\react-packager\src\Resolver\polyfills\prelude_dev.js)

**Comment by mwcampbell** [comment]
I'm having the same problem.

**Comment by rozele** [comment]
Hey @mwcampbell and @pkovacevic, we have actually seen this issue before as well.  It comes down to the case sensitivity of the "__dirname" in Node.js, which always returns a lowercase drive letter (i.e., c:\react-native).  The path pattern matching mechanisms used throughout the packager server are case sensitive.  Thus, if the current working directory of the Command Prompt you are running the packager from uses an uppercase drive letter (i.e., C:\react-native), then some of the imports and module discovery mechanisms will not work properly.

We're still looking into the best way to fix this deeply (rather than just applying `toLowerCase` BAND-AIDs all over the place). In the meantime, when you open Command Prompt, can you navigate to react-native root directory using the full path with the lowercase drive letter (i.e., `cd c:\react-native`).  This should hopefully unblock you.

**Comment by pkovacevic** [comment]
Amazing. Works. Thank you very much!

**Comment by mwcampbell** [comment]
Works for me too.

**Comment by mpodwysocki** [comment]
Fixed in scripts by #393
