### ISSUE TITLE
Roadmap For Missing Features and Plans to Merge?

### ISSUE THREAD

**Issue by joewood** [ReactWindows/react-native#422]
Is there a roadmap of missing features? 
Is the plan to merge this with the upstream or maintain as a pluggable platform? I would like to start using it and contributing but I need some merges from the upstream code (and React 15 merger).
This repo seems to have gone a little quiet recently, has the activity moved to a different repository?

**Comment by rozele** [comment]
Thanks Joe for the comment.  Our small team has been on vacation and travel over the past few weeks, which is why there has been an ebb in activity.  We're still hacking away here in the ReactWindows org!

The plan is to maintain as a pluggable platform, and there are a few things that we're trying to get squared away to support that (i.e., we'll likely use RNPM as a way to plug in commands to the CLI and we're looking at abstracting some of the cross-plat modules into base classes and *.platform.js files).

I'll take a look this week at getting rebased for the React 15 merger.

**Comment by joewood** [comment]
That's good news. I guess the react-native core repo will need some sort of `react-native platform add` type of command, similar to Cordova. Pragmatically, it may be easier to convince Facebook to merge in the platform code with first-class support. Also, looks like **rnpm** is [being merged](https://github.com/facebook/react-native/pull/7550) into **react-native-cli**.

Also, it would be useful for some background into the technical design and architecture. For example, I notice that react-native windows uses a .NET based bridge, rather than the cross platform C++ native bridge used in react-native common.

**Comment by rozele** [comment]
Hey @joewood, I just finished the rebase from https://github.com/facebook/react-native, so hopefully this unblocks you.  Would love to have your contributions!

The architecture is basically the same as the ReactAndroid implementation.  We may eventually consider embracing the cross-platform C++ native bridge, however, for now the JavaScript runtime for ReactWindows is Chakra.  We do plan to create an analogous wrapper to the cross-platform bridge for Chakra in C++, but have not got around to it.  The primary reason for the wrapper will be to prevent reading the bundle into the managed heap, but I'm sure there are plenty of other performance benefits.

**Comment by joewood** [comment]
That's great, thanks @rozele
